### ISSUE TITLE
GraphQL dependency update (0.8.*)

### ISSUE THREAD

**Issue by fstojanac** [tjmehta/graphql-parse-fields#3]
This library needs to be updated to support new GraphQL as the resolve function's info.fieldASTs value has been renamed to info.fieldNodes [(#554)](https://github.com/graphql/graphql-js/pull/554)

**Comment by mjurincic** [comment]
We just updated to v0.8.2 graphql and using graphql-parse-fields in our project this fix would be really appreciated.

**Comment by tjmehta** [comment]
Added support in `graphql-parse-fields@1.2.0`
