### ISSUE TITLE
Feature request: parse arguments

### ISSUE THREAD

**Issue by alekbarszczewski** [tjmehta/graphql-parse-fields#9]
Hey, thanks for this lib, it is very useful!

It would be even better if there was a way to parse arguments. While resolver function receives `args` argument it contains only arguments for "current" field. There isn't easy way to parse arguments for nested fields (they might be inside variables, they might have default values and might be nested objects). I can imagine something like this: `getArguments(info, 'some.nested.path')`.

Cheers

**Comment by tjmehta** [comment]
@alekbarszczewski thanks!

Sorry for the delay, this issue slipped under my radar. I haven't hit that situation myself, but it sounded like [keypather](https://github.com/tjmehta/keypather) might solve your problem. Check it out and let me know. Good luck.

**Comment by tjmehta** [comment]
Feel reopen if that doesn't work out for you!
